task: detection

# num_classes: 80
# remap_mscoco_category: True
num_classes: 5
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection

    img_folder: /mnt/h1/night_dataset/mix

    radar_folder: /mnt/h1/night_dataset/radar

    ann_file: /mnt/h1/night_dataset/mix/train_day3_night1.json
    sample_ratio: 1
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 1
  num_workers: 10
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection

    img_folder: /mnt/h1/night_dataset/mix

    radar_folder: /mnt/h1/night_dataset/radar

    ann_file: /mnt/h1/night_dataset/mix/val_day1_night1.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2 #64
  num_workers: 10
  drop_last: False