camera_topic: /aravis_cam/image_color
radar_topic: /radar/point_cloud_object
echo_topic: /traffic_echo
track_topic: /traffic_track
radar_project_topic: /traffic_radar_project
optimize_target_topic: /traffic_optimize_target
final_topic: /traffic_final
fps: 20
stats_interval_seconds: 15
radar_track_enabled: false
optimize: true
model_enabled: true
model:
  modality: camera
  path: yolo11x.pt
  config_path: configs/rtdetr/rtdetr_r50vd_6x_coco.yml
  checkpoint_path: configs/checkpoints/num_class_5__remap_mscoco_False.pth
  conf_thresh: 0.65
  classes:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
camera:
  extrinsic_matrix:
  - - -0.02446266658172008
    - -0.9994928600208532
    - 0.020385536380677596
    - -0.040298618376255035
  - - -0.11383272437059197
    - -0.017474107478906632
    - -0.9933462597183046
    - 4.999998569488525
  - - 0.9931987397690962
    - -0.02662043908827751
    - -0.11334753544006711
    - -0.5
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  camera_matrix:
  - - 2413.911679
    - 0.0
    - 1059.332971
  - - 0.0
    - 2161.173075
    - 745.776449
  - - 0.0
    - 0.0
    - 1.0
  width: 2048
  height: 1536
